# Build and Deploy Workflow
name: Build and Deploy

# Trigger the workflow on push to main branch and pull requests
on:
  push:
    branches: [main]
  workflow_dispatch:

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: pages
  cancel-in-progress: true

# Define the jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      # Install dependencies
      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Run the build process
      - name: Build
        run: npm run build

      # Verify build output
      - name: Verify dist
        run: |
          if [ ! -d dist ] || [ -z "$(ls -A dist)" ]; then
            echo "dist is missing or empty"
            exit 1
          fi
          echo "dist contents:"
          ls -1 dist

      # Upload artifact to GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  # Deploy to GitHub Pages using official action
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # Deploy to GitHub Pages
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
